services:
  localstack:
    container_name: dev_localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}
      - DEBUG=1
      - SERVICES=s3,sqs,sns,dynamodb,lambda,secretsmanager,iam,cloudwatch,logs,events,kms,ssm,kinesis,stepfunctions,apigateway
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./infra/localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge